### ISSUE TITLE
S11 modelling of the calibration loads

### ISSUE THREAD

**Issue by nmahesh1412** [edges-collab/edges-cal#45]
![image](https://user-images.githubusercontent.com/37714229/95498116-31127f80-0958-11eb-9f94-2bf0b49d8f72.png)

versus the plots when on 'faster-mode' branch;
![image](https://user-images.githubusercontent.com/37714229/95498208-52736b80-0958-11eb-91d7-24fc28eae85b.png)

The call & directory info: calobs_rcv1_2020_08 = ec.CalibrationObservation(path="/data5/edges/data/CalibrationObservations/Receiver01//Receiver01_25C_2020_08_25_040_to_200MHz",f_low = 50, f_high= 190, cterms=7,wterms=7, resistance_f=49.98,run_num=1,s11_kwargs = {"resistance":50.15},load_s11s = {"open": {"n_terms":151}},include_previous=False,compile_from_def=False)

**Comment by steven-murray** [comment]
This was fixed.
