### ISSUE TITLE
Reporting Script

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/edges-cal#48]
I think it would be super nice to be able to do a quick "report" on a lab-calibration based on a template. This would mean we could easily (with one command) run a report on a given calibration observation, producing both a Jupyter notebook and a PDF report. 
This would make it much easier to compare and contrast different observations over time. 

Some features I think should be included:

In the report:
 - Full print-out of metadata (chosen parameters, eg, wterms and cterms, as well as set parameters)
 - S11 measurements
 - Spectrum measurements
 - Calibration Coefficients
 - Any antenna simulators that are available.
 - Automatic detection of strangeness in any of the input data (including auxiliary data)

Other features:
  - Ability to turn on/off production of the PDF
  - Automatic report naming
  - Ability to automatically *publish* to the memo series.
  - Ability to run it in "diff" mode, in which two observations are calibrated and contrasted in the report (maybe even more than two...). In this case, metadata that is different between the two should be highlighted.

Most of the infrastructure for this is already in place. After discussions today in which it was difficult to locate memos and info on different historical calibrations, I think this will be incredibly helpful. Looking for other feature suggestions from @nmahesh1412 , @jdbowman etc.

**Comment by nmahesh1412** [comment]
Hi Steven,
   That is a brilliant idea. And would save a lot of time. The template I
have been using so far is similar to the one I sent out today or any of the
"Receiverxx_calubration" reports you see on the loco page. If we cover the
stuff that is there in those, the report should be good and complete.




Nivedita Mahesh
PhD Candidate, Astrophysics,
Low Frequency Cosmology Group,
School of Earth and Space Exploration,
VP of Professional Development, GPSA,
Arizona State University, Tempe.
EDGES: http://loco.lab.asu.edu/
