### ISSUE TITLE
Add readme on the usage of how to create calibration report

### ISSUE THREAD

**Issue by nmahesh1412** [edges-collab/edges-cal#58]
edges-cal report PATH --config CONFIGPATH

(the PATH is the path to a calibration observation, and CONFIGPATH is optional, but points to a YAML configuration file that specifies things like f_low, f_high and the male/female resistance).

Furthermore, you can also run a comparison between observations. This is intended to more easily show up what might be wrong in an observation, when compared to a "golden" observation for example. To run this:

edges-cal compare PATH CMPPATH --config CONFIGPATH --config-cmp CONFIGPATH

The reports are automatically output as both Jupyter notebooks and PDFs (the PDFs can be uploaded to the memo series).

**Comment by steven-murray** [comment]
This exists to some degree already in the readme. I've just added a tiny bit more detail to it. Any more you'd like to see?
