### ISSUE TITLE
From edges-analysis: total power filter

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/edges-cal#9]
In `edges-analysis` there is the possibility of doing a total power filter when averaging calibration spectra. Here's the code:

```
	# total power filter
	# ------------------
	tp = np.sum(ta_sel1, axis=1)
	W  = np.ones(len(tp))
	IN = np.arange(len(tp))
	
	Nsigma_tp = 3
	bad_old   = -1
	bad       =  0		
	iteration =  0
	
	

	while (bad > bad_old):

		iteration = iteration + 1
		print('Iteration: ' + str(iteration))
			
		std = np.std(tp[W>0])
		ave = np.mean(tp[W>0])
		res = tp-ave	

		IN_bad    = IN[(np.abs(res) > Nsigma_tp*std)]
		W[IN_bad] = 0
		
		bad_old = np.copy(bad)
		bad     = len(IN_bad)

		print('STD: ' + str(np.round(std,3)) + ' K')
		print('Number of bad points excised: ' + str(bad))
		print(IN_bad)
```

And in its original context: https://github.com/edges-collab/edges-analysis/blob/ac17ed386f4dfdccc8872d6fdf7d0926d899fecd/src/edges_analysis/basic.py#L1006

@gitul : is this useful to keep in this code?

**Comment by gitul** [comment]
Yes Steven, I would like to keep this filter if possible.

Thank you
Raul


ps: I don't know if a simple email reply is the right way to reply to git comments/questions.



On 02/11/2020 03:47 PM, Steven Murray wrote:

In edges-analysis there is the possibility of doing a total power filter when averaging calibration spectra. Here's the code:

        # total power filter
        # ------------------
        tp = np.sum(ta_sel1, axis=1)
        W  = np.ones(len(tp))
        IN = np.arange(len(tp))

        Nsigma_tp = 3
        bad_old   = -1
        bad       =  0
        iteration =  0



        while (bad > bad_old):

                iteration = iteration + 1
                print('Iteration: ' + str(iteration))

                std = np.std(tp[W>0])
                ave = np.mean(tp[W>0])
                res = tp-ave

                IN_bad    = IN[(np.abs(res) > Nsigma_tp*std)]
                W[IN_bad] = 0

                bad_old = np.copy(bad)
                bad     = len(IN_bad)

                print('STD: ' + str(np.round(std,3)) + ' K')
                print('Number of bad points excised: ' + str(bad))
                print(IN_bad)


And in its original context: https://github.com/edges-collab/edges-analysis/blob/ac17ed386f4dfdccc8872d6fdf7d0926d899fecd/src/edges_analysis/basic.py#L1006

@gitul<https://github.com/gitul> : is this useful to keep in this code?

**Comment by steven-murray** [comment]
@gitul excellent, thanks. I'll work it into `edges-cal`. 

PS: yes, you can reply via email, though usually clicking the link to go to the issue on Github gives you more options and better formatting :-)

**Comment by steven-murray** [comment]
This seems to be more pertinent to field data than lab data, so I will leave it in `edges-analysis`.
